#!/bin/sh
# open-vm-tools vgauth

# Load SMF shell support definitions
. /lib/svc/share/smf_include.sh

METHOD="$1"

if [ -z $SMF_FMRI ]
then
    echo "SMF framework variables are not initialized."
    exit $SMF_EXIT_ERR
fi

set -f

case "$METHOD" in
    start)
        # start daemon
        /usr/bin/VGAuthService -b
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    stop)
        # stop daemon
        /usr/bin/VGAuthService -k
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    restart)
        # stop daemon
        /usr/bin/VGAuthService -k
        /usr/bin/VGAuthService -s
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    *)
        echo "Usage: $0 { start | stop }" >&2
        echo " unknow method $1" >&2
        exit $SMF_EXIT_ERR_FATAL
        ;;
esac

exit $SMF_EXIT_ERR_FATAL
