#!/bin/sh
# open-vm-tools vmtoolsd

# Load SMF shell support definitions
. /lib/svc/share/smf_include.sh

METHOD="$1"

if [ -z $SMF_FMRI ]
then
    echo "SMF framework variables are not initialized."
    exit $SMF_EXIT_ERR
fi

set -f
set -- --pidfile /var/run/vmtoolsd.pid

case "$METHOD" in
    start)
        # Enable or disable shares depending if running on ESXi Server
        /usr/bin/vmware-checkvm -p | grep -q ESX
        if [ $? = 0 ]
        then
            svcadm disable svc:/vmware/shares:default
        else
            svcadm enable svc:/vmware/shares:default
        fi
        # start daemon
        /usr/bin/vmtoolsd -b /var/run/vmtoolsd.pid
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    stop)
        # stop daemon
        [ -f /var/run/vmtoolsd.pid ] && kill `cat /var/run/vmtoolsd.pid`
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    restart)
        # stop daemon
        [ -f /var/run/vmtoolsd.pid ] && kill `cat /var/run/vmtoolsd.pid`
        /usr/bin/vmtoolsd -b /var/run/vmtoolsd.pid
        [ $? = 0 ] && exit $SMF_EXIT_OK
        ;;

    *)
        echo "Usage: $0 { start | stop }" >&2
        echo " unknow method $1" >&2
        exit $SMF_EXIT_ERR_FATAL
        ;;
esac

exit $SMF_EXIT_ERR_FATAL
